-- 코드를 입력하세요
# SELECT INS.ANIMAL_ID, INS.NAME
# FROM ANIMAL_INS INS
# INNER JOIN ANIMAL_OUTS OUTS
# ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
# WHERE INS.DATETIME > OUTS.DATETIME
# ORDER BY INS.DATETIME

SELECT A.ANIMAL_ID, A.NAME 
FROM ANIMAL_INS A LEFT JOIN ANIMAL_OUTS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.DATETIME > B.DATETIME
ORDER BY A.DATETIME;